### ISSUE TITLE
Code Review chapter point to the Turing Way

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/guide#214] opened 2020-05-06 13:58 UTC
The [guide](https://guide.esciencecenter.nl/#/best_practices/code_review) and [The Turing Way](https://the-turing-way.netlify.app/reviewing/reviewing.html) both have a a chapter on code reviews.

* To reduce maintenance cost on the guide we should replace text with link to the turing way from the guide
* Any content about code review that is in the guide, but missing in the Turing way should be added to the Turing Way via a PR
* Any content about code reviewing that is center specific should stay in the guide.

**Comment by SarahAlidoost** [comment] 2020-09-09 13:59
Here a comparison between sections in the **guide** and **The Turing Way**:

| Guide | Turing | 
|---|---|
| Introduction | Summary |
| X | Importance and Personal Benefits |
| Process | Recommendations and best practices |
| Approach, Prerequisites, Providing feedback | Typical workflows |
| Review checklist | X |
| X | Checklist for code review process |
| Program level checklist | X |
| File/Change level checklist | X |
| References | Resources for code reviewing (incomplete) |

The two sections [Program level checklist ](https://guide.esciencecenter.nl/#/best_practices/code_review?id=program-level-checklist)and [File/Change level checklist ](https://guide.esciencecenter.nl/#/best_practices/code_review?id=filechange-level-checklist) from the **guide** are moved to **The Turing Way.** The section Review checklist, in particular, the [Rubric for assessing code quality](https://guide.esciencecenter.nl/#/best_practices/code_review?id=rubric-for-assessing-code-quality) is more related to the code quality chapter than the code review chapter. Also, there is already [an issue](https://github.com/alan-turing-institute/the-turing-way/issues/656) about code review chapter in **The Turing Way** repo. I commented about these changes and make a [draft PR ](https://github.com/alan-turing-institute/the-turing-way/pull/1320) there.

**Comment by SarahAlidoost** [comment] 2020-11-06 16:36
@c-martinez The [pull request](https://github.com/alan-turing-institute/the-turing-way/pull/1320) is ready for a review. The section **Acknowledging contributors** in the PR template needs to be updated. Do you know who are the original authors of the chapter in the guide? thanks.

**Comment by egpbos** [comment] 2022-04-07 19:04
Was there anything left in our code review chapter that we should keep? It seems most has been moved to The Turing Way.

**Comment by c-martinez** [comment] 2022-04-08 07:31
No, since Turing Way PR has been merged, the only thing left would be to clean up this section and point there. Something like:

"At the eScience Center, we value software quality. You can read more about it [here](https://the-turing-way.netlify.app/reproducible-research/reviewing.html)"

**Comment by bouweandela** [comment] 2023-09-20 11:03
We will just remove the chapter from the guide.

**Closed by bouweandela** 2023-09-20 11:03 UTC
Labels: turing way
