### ISSUE TITLE
Contact person code of conduct

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#139] opened 2018-06-25 08:32 UTC
The guide tells us to have a code of conduct and to use the one from https://www.contributor-covenant.org/
You have to add an email address to contact in case of violations of the code of conduct:
```
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team at [INSERT EMAIL ADDRESS]. 
```
Can we give some advice on whose email address to put there? Should this be the PI? Or can it be an engineer? Maybe the eScience project coordinator?

**Comment by vincentvanhees** [comment] 2018-06-25 09:34
Hi Janneke, while you are looking into this, maybe also check whether you can merge this into the guide : https://github.com/NLeSC/code-of-conduct/pull/1 or remove the code-of-conduct repository.

**Comment by jvdzwaan** [comment] 2018-06-26 07:10
Hi @vincentvanhees, this code of conduct seems obsolete to me. It is shorter than the text from https://www.contributor-covenant.org/, but I see advantages in adopting a standard text.

About the issue I posted, I don't think this is something a single person can decide. I was hoping to start a discussion. Who can we make responsible for this? ;)

**Comment by vincentvanhees** [comment] 2018-06-26 08:03
I think the text is intended to de-escalate problems, so the project coordinator is probably the most natural choice. Alternatively, I think Aletta could be an option. Maybe good to discuss with an MT member.

**Comment by jspaaks** [comment] 2018-06-26 09:30
FYI for xenon, we created xenon@esciencecenter.nl
https://github.com/NLeSC/Xenon/blame/446a716688e98088cf81760f60a846baa5d21d4b/CODE_OF_CONDUCT.md#L58

**Comment by jvdzwaan** [comment] 2018-06-26 09:31
And who reads the email send to this address?

**Comment by bouweandela** [comment] 2018-06-26 11:54
Duplicate of #14

**Closed by bouweandela** 2018-06-26 11:54 UTC
