### ISSUE TITLE
Documentation chapter

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#385] opened 2024-12-03 14:47 UTC
- [x] Update where necessary & move to Turing Way. #361
- [x] Add a section to Best Practices.
- [x] Remove the chapter
- [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)

**Comment by bouweandela** [comment] 2024-12-06 11:13
Duplicate of #361?

**Comment by egpbos** [comment] 2024-12-06 14:22
Awesome, indeed! #361 covers task one in this issue. I will close that one and finish the rest of this one.

**Closed** 2024-12-10 15:23 UTC
Labels: dash
